
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ALERTA AND ARROW COLON COMMA DEF DESLIGAR DIFUNDIR DISPOSITIVOS EM EQUALS EXECUTE FALSE FIMDISPOSITIVOS ID_DEV_ICE ID_OBS LBRACKET LIGAR MSG NUM OP_LOGIC PARA QUANDO RBRACKET SEMICOLON SENAO TRUEprogram : dev_sec cmd_secdev_sec : DISPOSITIVOS COLON dev_list FIMDISPOSITIVOSdev_list : device dev_list\n                | devicedevice : id_devicedevice : id_device LBRACKET ID_OBS RBRACKETid_device : ID_OBScmd_sec : cmd_listcmd_list : cmd SEMICOLON cmd_list\n                | cmd SEMICOLONcmd : attrib\n           | obsact\n           | actattrib : DEF ID_OBS EQUALS valobsact : QUANDO obs COLON actobsact : QUANDO obs COLON act SENAO actobs : ID_OBS OP_LOGIC valobs : ID_OBS OP_LOGIC val AND obsval : NUMval : boolbool : TRUE\n            | FALSEact : EXECUTE action EM id_deviceaction : LIGAR\n              | DESLIGARact : ALERTA PARA id_device COLON MSGact : ALERTA PARA id_device COLON MSG COMMA ID_OBSact : DIFUNDIR COLON MSG ARROW LBRACKET dev_list_n RBRACKETact : DIFUNDIR COLON MSG ID_OBS ARROW LBRACKET dev_list_n RBRACKETdev_list_n : id_devicedev_list_n : id_device COMMA dev_list_n'
    
_lr_action_items = {'DISPOSITIVOS':([0,],[3,]),'$end':([1,4,5,16,29,],[0,-1,-8,-10,-9,]),'DEF':([2,16,36,],[10,10,-2,]),'QUANDO':([2,16,36,],[11,11,-2,]),'EXECUTE':([2,16,31,36,51,],[12,12,12,-2,12,]),'ALERTA':([2,16,31,36,51,],[13,13,13,-2,13,]),'DIFUNDIR':([2,16,31,36,51,],[14,14,14,-2,14,]),'COLON':([3,14,18,28,34,40,41,42,43,45,58,],[15,24,31,-7,47,-19,-20,-21,-22,-17,-18,]),'SEMICOLON':([6,7,8,9,28,39,40,41,42,43,44,46,53,57,63,64,68,],[16,-11,-12,-13,-7,-14,-19,-20,-21,-22,-15,-23,-26,-16,-27,-28,-29,]),'ID_OBS':([10,11,15,23,26,27,28,33,35,38,52,54,56,59,62,65,],[17,19,28,28,28,-5,-7,28,49,50,19,28,-6,63,28,28,]),'LIGAR':([12,],[21,]),'DESLIGAR':([12,],[22,]),'PARA':([13,],[23,]),'EQUALS':([17,],[30,]),'OP_LOGIC':([19,],[32,]),'EM':([20,21,22,],[33,-24,-25,]),'MSG':([24,47,],[35,53,]),'FIMDISPOSITIVOS':([25,26,27,28,37,56,],[36,-4,-5,-7,-3,-6,]),'LBRACKET':([27,28,48,55,],[38,-7,54,62,]),'SENAO':([28,44,46,53,63,64,68,],[-7,51,-23,-26,-27,-28,-29,]),'COMMA':([28,53,61,],[-7,59,65,]),'RBRACKET':([28,50,60,61,66,67,],[-7,56,64,-30,68,-31,]),'NUM':([30,32,],[40,40,]),'TRUE':([30,32,],[42,42,]),'FALSE':([30,32,],[43,43,]),'ARROW':([35,49,],[48,55,]),'AND':([40,41,42,43,45,],[-19,-20,-21,-22,52,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'dev_sec':([0,],[2,]),'cmd_sec':([2,],[4,]),'cmd_list':([2,16,],[5,29,]),'cmd':([2,16,],[6,6,]),'attrib':([2,16,],[7,7,]),'obsact':([2,16,],[8,8,]),'act':([2,16,31,51,],[9,9,44,57,]),'obs':([11,52,],[18,58,]),'action':([12,],[20,]),'dev_list':([15,26,],[25,37,]),'device':([15,26,],[26,26,]),'id_device':([15,23,26,33,54,62,65,],[27,34,27,46,61,61,61,]),'val':([30,32,],[39,45,]),'bool':([30,32,],[41,41,]),'dev_list_n':([54,62,65,],[60,66,67,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> dev_sec cmd_sec','program',2,'p_program','obsact_parser.py',79),
  ('dev_sec -> DISPOSITIVOS COLON dev_list FIMDISPOSITIVOS','dev_sec',4,'p_dev_sec','obsact_parser.py',83),
  ('dev_list -> device dev_list','dev_list',2,'p_dev_list','obsact_parser.py',87),
  ('dev_list -> device','dev_list',1,'p_dev_list','obsact_parser.py',88),
  ('device -> id_device','device',1,'p_device_simple','obsact_parser.py',95),
  ('device -> id_device LBRACKET ID_OBS RBRACKET','device',4,'p_device_with_sensor','obsact_parser.py',99),
  ('id_device -> ID_OBS','id_device',1,'p_id_device','obsact_parser.py',103),
  ('cmd_sec -> cmd_list','cmd_sec',1,'p_cmd_sec','obsact_parser.py',108),
  ('cmd_list -> cmd SEMICOLON cmd_list','cmd_list',3,'p_cmd_list','obsact_parser.py',112),
  ('cmd_list -> cmd SEMICOLON','cmd_list',2,'p_cmd_list','obsact_parser.py',113),
  ('cmd -> attrib','cmd',1,'p_cmd','obsact_parser.py',120),
  ('cmd -> obsact','cmd',1,'p_cmd','obsact_parser.py',121),
  ('cmd -> act','cmd',1,'p_cmd','obsact_parser.py',122),
  ('attrib -> DEF ID_OBS EQUALS val','attrib',4,'p_attrib','obsact_parser.py',126),
  ('obsact -> QUANDO obs COLON act','obsact',4,'p_obsact_simple','obsact_parser.py',130),
  ('obsact -> QUANDO obs COLON act SENAO act','obsact',6,'p_obsact_with_else','obsact_parser.py',134),
  ('obs -> ID_OBS OP_LOGIC val','obs',3,'p_obs_simple','obsact_parser.py',138),
  ('obs -> ID_OBS OP_LOGIC val AND obs','obs',5,'p_obs_and','obsact_parser.py',142),
  ('val -> NUM','val',1,'p_val_num','obsact_parser.py',146),
  ('val -> bool','val',1,'p_val_bool','obsact_parser.py',150),
  ('bool -> TRUE','bool',1,'p_bool','obsact_parser.py',154),
  ('bool -> FALSE','bool',1,'p_bool','obsact_parser.py',155),
  ('act -> EXECUTE action EM id_device','act',4,'p_act_execute','obsact_parser.py',159),
  ('action -> LIGAR','action',1,'p_action','obsact_parser.py',163),
  ('action -> DESLIGAR','action',1,'p_action','obsact_parser.py',164),
  ('act -> ALERTA PARA id_device COLON MSG','act',5,'p_act_alert_simple','obsact_parser.py',168),
  ('act -> ALERTA PARA id_device COLON MSG COMMA ID_OBS','act',7,'p_act_alert_with_var','obsact_parser.py',172),
  ('act -> DIFUNDIR COLON MSG ARROW LBRACKET dev_list_n RBRACKET','act',7,'p_act_broadcast_simple','obsact_parser.py',176),
  ('act -> DIFUNDIR COLON MSG ID_OBS ARROW LBRACKET dev_list_n RBRACKET','act',8,'p_act_broadcast_with_var','obsact_parser.py',180),
  ('dev_list_n -> id_device','dev_list_n',1,'p_dev_list_n_single','obsact_parser.py',184),
  ('dev_list_n -> id_device COMMA dev_list_n','dev_list_n',3,'p_dev_list_n_multiple','obsact_parser.py',188),
]
