
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ALERTA AND ARROW BOOL COLON COMMA DEF DESLIGAR DIFUNDIR DISPOSITIVOS EM EQUAL EXECUTE FIMDISPOSITIVOS ID_DEV_ICE ID_OBS LBRACKET LIGAR MSG NUMBER OPLOGIC PARA QUANDO RBRACKET SEMICOLON SENAOprogram : dev_sec cmd_secdev_sec : DISPOSITIVOS COLON dev_list FIMDISPOSITIVOSdev_list : dev_ice dev_listdev_list : dev_icedev_ice : ID_DEV_ICEdev_ice : ID_DEV_ICE LBRACKET ID_OBS RBRACKET\n| ID_DEV_ICE LBRACKET ID_DEV_ICE RBRACKETcmd_sec : cmd_listcmd_list : cmd SEMICOLON cmd_listcmd_list : cmd SEMICOLONcmd : attrib\n| obsact\n| actattrib : DEF ID_OBS EQUAL val\n| DEF ID_DEV_ICE EQUAL valval : NUMBERval : BOOLobsact : QUANDO obs COLON actobsact : QUANDO obs COLON act SENAO actobs : ID_OBS OPLOGIC val\n| ID_DEV_ICE OPLOGIC valobs : ID_OBS OPLOGIC val AND obs\n| ID_DEV_ICE OPLOGIC val AND obsact : EXECUTE action EM ID_DEV_ICEaction : LIGARaction : DESLIGARact : ALERTA PARA ID_DEV_ICE COLON MSGact : ALERTA PARA ID_DEV_ICE COLON MSG COMMA ID_OBS\n| ALERTA PARA ID_DEV_ICE COLON MSG COMMA ID_DEV_ICEact : DIFUNDIR COLON MSG ARROW LBRACKET dev_list_n RBRACKETact : DIFUNDIR COLON MSG ID_OBS ARROW LBRACKET dev_list_n RBRACKET\n| DIFUNDIR COLON MSG ID_DEV_ICE ARROW LBRACKET dev_list_n RBRACKETdev_list_n : ID_DEV_ICEdev_list_n : ID_DEV_ICE COMMA dev_list_n'
    
_lr_action_items = {'DISPOSITIVOS':([0,],[3,]),'$end':([1,4,5,16,30,],[0,-1,-8,-10,-9,]),'DEF':([2,16,39,],[10,10,-2,]),'QUANDO':([2,16,39,],[11,11,-2,]),'EXECUTE':([2,16,33,39,56,],[12,12,12,-2,12,]),'ALERTA':([2,16,33,39,56,],[13,13,13,-2,13,]),'DIFUNDIR':([2,16,33,39,56,],[14,14,14,-2,14,]),'COLON':([3,14,19,37,43,44,47,48,66,67,],[15,26,33,50,-16,-17,-20,-21,-22,-23,]),'SEMICOLON':([6,7,8,9,42,43,44,45,46,49,59,65,73,74,75,80,81,],[16,-11,-12,-13,-14,-16,-17,-15,-18,-24,-27,-19,-29,-28,-30,-31,-32,]),'ID_OBS':([10,11,38,41,57,58,68,],[17,20,52,55,20,20,74,]),'ID_DEV_ICE':([10,11,15,25,28,29,36,38,41,57,58,60,63,64,68,71,72,76,],[18,21,29,37,29,-5,49,53,54,21,21,70,-7,-6,73,70,70,70,]),'LIGAR':([12,],[23,]),'DESLIGAR':([12,],[24,]),'PARA':([13,],[25,]),'EQUAL':([17,18,],[31,32,]),'OPLOGIC':([20,21,],[34,35,]),'EM':([22,23,24,],[36,-25,-26,]),'MSG':([26,50,],[38,59,]),'FIMDISPOSITIVOS':([27,28,29,40,63,64,],[39,-4,-5,-3,-7,-6,]),'LBRACKET':([29,51,61,62,],[41,60,71,72,]),'NUMBER':([31,32,34,35,],[43,43,43,43,]),'BOOL':([31,32,34,35,],[44,44,44,44,]),'ARROW':([38,52,53,],[51,61,62,]),'AND':([43,44,47,48,],[-16,-17,57,58,]),'SENAO':([46,49,59,73,74,75,80,81,],[56,-24,-27,-29,-28,-30,-31,-32,]),'RBRACKET':([54,55,69,70,77,78,79,],[63,64,75,-33,80,81,-34,]),'COMMA':([59,70,],[68,76,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'dev_sec':([0,],[2,]),'cmd_sec':([2,],[4,]),'cmd_list':([2,16,],[5,30,]),'cmd':([2,16,],[6,6,]),'attrib':([2,16,],[7,7,]),'obsact':([2,16,],[8,8,]),'act':([2,16,33,56,],[9,9,46,65,]),'obs':([11,57,58,],[19,66,67,]),'action':([12,],[22,]),'dev_list':([15,28,],[27,40,]),'dev_ice':([15,28,],[28,28,]),'val':([31,32,34,35,],[42,45,47,48,]),'dev_list_n':([60,71,72,76,],[69,77,78,79,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> dev_sec cmd_sec','program',2,'p_program','obsact_parser.py',12),
  ('dev_sec -> DISPOSITIVOS COLON dev_list FIMDISPOSITIVOS','dev_sec',4,'p_dev_sec','obsact_parser.py',53),
  ('dev_list -> dev_ice dev_list','dev_list',2,'p_dev_list_multiple','obsact_parser.py',57),
  ('dev_list -> dev_ice','dev_list',1,'p_dev_list_single','obsact_parser.py',61),
  ('dev_ice -> ID_DEV_ICE','dev_ice',1,'p_dev_ice_simple','obsact_parser.py',65),
  ('dev_ice -> ID_DEV_ICE LBRACKET ID_OBS RBRACKET','dev_ice',4,'p_dev_ice_obs','obsact_parser.py',69),
  ('dev_ice -> ID_DEV_ICE LBRACKET ID_DEV_ICE RBRACKET','dev_ice',4,'p_dev_ice_obs','obsact_parser.py',70),
  ('cmd_sec -> cmd_list','cmd_sec',1,'p_cmd_sec','obsact_parser.py',76),
  ('cmd_list -> cmd SEMICOLON cmd_list','cmd_list',3,'p_cmd_list_multiple','obsact_parser.py',80),
  ('cmd_list -> cmd SEMICOLON','cmd_list',2,'p_cmd_list_single','obsact_parser.py',84),
  ('cmd -> attrib','cmd',1,'p_cmd','obsact_parser.py',88),
  ('cmd -> obsact','cmd',1,'p_cmd','obsact_parser.py',89),
  ('cmd -> act','cmd',1,'p_cmd','obsact_parser.py',90),
  ('attrib -> DEF ID_OBS EQUAL val','attrib',4,'p_attrib','obsact_parser.py',96),
  ('attrib -> DEF ID_DEV_ICE EQUAL val','attrib',4,'p_attrib','obsact_parser.py',97),
  ('val -> NUMBER','val',1,'p_val_number','obsact_parser.py',104),
  ('val -> BOOL','val',1,'p_val_bool','obsact_parser.py',108),
  ('obsact -> QUANDO obs COLON act','obsact',4,'p_obsact_simple','obsact_parser.py',113),
  ('obsact -> QUANDO obs COLON act SENAO act','obsact',6,'p_obsact_senao','obsact_parser.py',119),
  ('obs -> ID_OBS OPLOGIC val','obs',3,'p_obs_simple','obsact_parser.py',127),
  ('obs -> ID_DEV_ICE OPLOGIC val','obs',3,'p_obs_simple','obsact_parser.py',128),
  ('obs -> ID_OBS OPLOGIC val AND obs','obs',5,'p_obs_and','obsact_parser.py',132),
  ('obs -> ID_DEV_ICE OPLOGIC val AND obs','obs',5,'p_obs_and','obsact_parser.py',133),
  ('act -> EXECUTE action EM ID_DEV_ICE','act',4,'p_act_execute','obsact_parser.py',140),
  ('action -> LIGAR','action',1,'p_action_ligar','obsact_parser.py',146),
  ('action -> DESLIGAR','action',1,'p_action_desligar','obsact_parser.py',150),
  ('act -> ALERTA PARA ID_DEV_ICE COLON MSG','act',5,'p_act_alerta','obsact_parser.py',155),
  ('act -> ALERTA PARA ID_DEV_ICE COLON MSG COMMA ID_OBS','act',7,'p_act_alerta_var','obsact_parser.py',162),
  ('act -> ALERTA PARA ID_DEV_ICE COLON MSG COMMA ID_DEV_ICE','act',7,'p_act_alerta_var','obsact_parser.py',163),
  ('act -> DIFUNDIR COLON MSG ARROW LBRACKET dev_list_n RBRACKET','act',7,'p_act_difundir','obsact_parser.py',171),
  ('act -> DIFUNDIR COLON MSG ID_OBS ARROW LBRACKET dev_list_n RBRACKET','act',8,'p_act_difundir_var','obsact_parser.py',179),
  ('act -> DIFUNDIR COLON MSG ID_DEV_ICE ARROW LBRACKET dev_list_n RBRACKET','act',8,'p_act_difundir_var','obsact_parser.py',180),
  ('dev_list_n -> ID_DEV_ICE','dev_list_n',1,'p_dev_list_n_single','obsact_parser.py',189),
  ('dev_list_n -> ID_DEV_ICE COMMA dev_list_n','dev_list_n',3,'p_dev_list_n_multiple','obsact_parser.py',193),
]
