
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftANDALERTA AND BOOL DEF DESLIGAR DIFUNDIR DISPOSITIVOS DP EM EQ EXECUTE FIMDISPOSITIVOS ID_DEV ID_OBS LIGAR LSQB MSG NUM OP_LOGIC PARA PONTOV QUANDO RSQB SENAO SETAB VIRGPROGRAM : DEV_SEC CMD_SECDEV_SEC : DISPOSITIVOS DP DEV_LIST FIMDISPOSITIVOSDEV_LIST : DEV_ITEMDEV_LIST : DEV_LIST DEV_ITEMDEV_ITEM : ID_DEVDEV_ITEM : ID_DEV LSQB ID_OBS RSQBCMD_SEC : CMD_SEC : CMD_LISTCMD_LIST : CMD PONTOVCMD_LIST : CMD_LIST CMD PONTOVCMD : DEF ID_OBS EQ VALCMD : QUANDO OBS DP ACTCMD : QUANDO OBS DP ACT SENAO ACTOBS : SIMPLE_OBSOBS : SIMPLE_OBS AND OBSSIMPLE_OBS : ID_OBS OP_LOGIC VALVAL : NUMVAL : BOOLACT : EXECUTE ACTION EM ID_DEVACT : ALERTA PARA ID_DEV DP MSGACT : ALERTA PARA ID_DEV DP MSG VIRG ID_OBSACT : DIFUNDIR DP MSG SETAB LSB_DEVLISTACT : DIFUNDIR DP MSG ID_OBS SETAB LSB_DEVLISTLSB_DEVLIST : LSQB DEV_LIST_N RSQBDEV_LIST_N : ID_DEVDEV_LIST_N : DEV_LIST_N VIRG ID_DEVACTION : LIGARACTION : DESLIGAR'
    
_lr_action_items = {'DISPOSITIVOS':([0,],[3,]),'$end':([1,2,4,5,11,19,24,],[0,-7,-1,-8,-9,-10,-2,]),'DEF':([2,5,11,19,24,],[7,7,-9,-10,-2,]),'QUANDO':([2,5,11,19,24,],[8,8,-9,-10,-2,]),'DP':([3,13,14,28,29,33,34,35,46,],[9,21,-14,-17,-18,42,-15,-16,49,]),'PONTOV':([6,10,27,28,29,30,44,48,52,53,59,60,61,],[11,19,-11,-17,-18,-12,-13,-19,-20,-22,-23,-21,-24,]),'ID_OBS':([7,8,22,26,47,56,],[12,15,15,36,51,60,]),'ID_DEV':([9,16,17,18,25,41,43,45,54,62,],[18,18,-3,-5,-4,46,-6,48,58,63,]),'EQ':([12,],[20,]),'AND':([14,28,29,35,],[22,-17,-18,-16,]),'OP_LOGIC':([15,],[23,]),'FIMDISPOSITIVOS':([16,17,18,25,43,],[24,-3,-5,-4,-6,]),'LSQB':([18,50,55,],[26,54,54,]),'NUM':([20,23,],[28,28,]),'BOOL':([20,23,],[29,29,]),'EXECUTE':([21,37,],[31,31,]),'ALERTA':([21,37,],[32,32,]),'DIFUNDIR':([21,37,],[33,33,]),'SENAO':([30,48,52,53,59,60,61,],[37,-19,-20,-22,-23,-21,-24,]),'LIGAR':([31,],[39,]),'DESLIGAR':([31,],[40,]),'PARA':([32,],[41,]),'RSQB':([36,57,58,63,],[43,61,-25,-26,]),'EM':([38,39,40,],[45,-27,-28,]),'MSG':([42,49,],[47,52,]),'SETAB':([47,51,],[50,55,]),'VIRG':([52,57,58,63,],[56,62,-25,-26,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'PROGRAM':([0,],[1,]),'DEV_SEC':([0,],[2,]),'CMD_SEC':([2,],[4,]),'CMD_LIST':([2,],[5,]),'CMD':([2,5,],[6,10,]),'OBS':([8,22,],[13,34,]),'SIMPLE_OBS':([8,22,],[14,14,]),'DEV_LIST':([9,],[16,]),'DEV_ITEM':([9,16,],[17,25,]),'VAL':([20,23,],[27,35,]),'ACT':([21,37,],[30,44,]),'ACTION':([31,],[38,]),'LSB_DEVLIST':([50,55,],[53,59,]),'DEV_LIST_N':([54,],[57,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> PROGRAM","S'",1,None,None,None),
  ('PROGRAM -> DEV_SEC CMD_SEC','PROGRAM',2,'p_PROGRAM','parser.py',14),
  ('DEV_SEC -> DISPOSITIVOS DP DEV_LIST FIMDISPOSITIVOS','DEV_SEC',4,'p_DEV_SEC','parser.py',22),
  ('DEV_LIST -> DEV_ITEM','DEV_LIST',1,'p_DEV_LIST_single','parser.py',26),
  ('DEV_LIST -> DEV_LIST DEV_ITEM','DEV_LIST',2,'p_DEV_LIST_many','parser.py',30),
  ('DEV_ITEM -> ID_DEV','DEV_ITEM',1,'p_DEV_ITEM_noobs','parser.py',34),
  ('DEV_ITEM -> ID_DEV LSQB ID_OBS RSQB','DEV_ITEM',4,'p_DEV_ITEM_obs','parser.py',38),
  ('CMD_SEC -> <empty>','CMD_SEC',0,'p_CMD_SEC_empty','parser.py',44),
  ('CMD_SEC -> CMD_LIST','CMD_SEC',1,'p_CMD_SEC','parser.py',48),
  ('CMD_LIST -> CMD PONTOV','CMD_LIST',2,'p_CMD_LIST_single','parser.py',62),
  ('CMD_LIST -> CMD_LIST CMD PONTOV','CMD_LIST',3,'p_CMD_LIST_many','parser.py',66),
  ('CMD -> DEF ID_OBS EQ VAL','CMD',4,'p_CMD_ATTR','parser.py',72),
  ('CMD -> QUANDO OBS DP ACT','CMD',4,'p_CMD_OBSACT_simple','parser.py',77),
  ('CMD -> QUANDO OBS DP ACT SENAO ACT','CMD',6,'p_CMD_OBSACT_else','parser.py',81),
  ('OBS -> SIMPLE_OBS','OBS',1,'p_OBS_simple','parser.py',87),
  ('OBS -> SIMPLE_OBS AND OBS','OBS',3,'p_OBS_and','parser.py',91),
  ('SIMPLE_OBS -> ID_OBS OP_LOGIC VAL','SIMPLE_OBS',3,'p_SIMPLE_OBS','parser.py',95),
  ('VAL -> NUM','VAL',1,'p_VAL_NUM','parser.py',101),
  ('VAL -> BOOL','VAL',1,'p_VAL_BOOL','parser.py',105),
  ('ACT -> EXECUTE ACTION EM ID_DEV','ACT',4,'p_ACT_execute','parser.py',111),
  ('ACT -> ALERTA PARA ID_DEV DP MSG','ACT',5,'p_ACT_alerta_simple','parser.py',115),
  ('ACT -> ALERTA PARA ID_DEV DP MSG VIRG ID_OBS','ACT',7,'p_ACT_alerta_obs','parser.py',119),
  ('ACT -> DIFUNDIR DP MSG SETAB LSB_DEVLIST','ACT',5,'p_ACT_difundir','parser.py',123),
  ('ACT -> DIFUNDIR DP MSG ID_OBS SETAB LSB_DEVLIST','ACT',6,'p_ACT_difundir_msg_obs','parser.py',129),
  ('LSB_DEVLIST -> LSQB DEV_LIST_N RSQB','LSB_DEVLIST',3,'p_LSB_DEVLIST','parser.py',137),
  ('DEV_LIST_N -> ID_DEV','DEV_LIST_N',1,'p_DEV_LIST_N_single','parser.py',141),
  ('DEV_LIST_N -> DEV_LIST_N VIRG ID_DEV','DEV_LIST_N',3,'p_DEV_LIST_N_many','parser.py',145),
  ('ACTION -> LIGAR','ACTION',1,'p_ACTION','parser.py',152),
  ('ACTION -> DESLIGAR','ACTION',1,'p_ACTION_desligar','parser.py',156),
]
